package com.froyo.ridekaro.helper

const val KEY_USER_LOGGED_IN = "DOESUSERLOGGEDIN"
const val KEY_DISPLAY_NAME = "KEY_DISPLAY_NAME"
const val KEY_USER_GOOGLE_ID = "GOOGLEUSERID"
const val KEY_LOGIN_WITH_OAUTH = "LOGINWITHOAUTH"
const val KEY_USER_GOOGLE_GMAIL = "GOOGLEUSERGMAIL"
const val USER_PHONE_LOGIN = "USER_PHONE_LOGIN"
